<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  0 => 
  array (
    'name' => 'General Phillipines chart of accounts.',
    'package' => 'chart_en_PH-general',
    'version' => '2.4.1-4',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'en_PH-general.sql',
  ),
  1 => 
  array (
    'name' => 'Theme Anterp',
    'package' => 'anterp',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/anterp',
  ),
  2 => 
  array (
    'name' => 'Theme Bluecollar',
    'package' => 'bluecollar',
    'version' => '2.4.0-3',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/bluecollar',
  ),
  3 => 
  array (
    'name' => 'Theme Classic',
    'package' => 'classic',
    'version' => '2.4.1-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/classic',
  ),
  4 => 
  array (
    'name' => 'Theme Dynamic',
    'package' => 'dynamic',
    'version' => '2.4.0-3',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/dynamic',
  ),
  5 => 
  array (
    'name' => 'Theme Elegant',
    'package' => 'elegant',
    'version' => '2.4.0-2',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/elegant',
  ),
  6 => 
  array (
    'name' => 'Theme Exclusive',
    'package' => 'exclusive',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/exclusive',
  ),
  7 => 
  array (
    'name' => 'Theme Exclusive for Dashboard',
    'package' => 'exclusive_db',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/exclusive_db',
  ),
  8 => 
  array (
    'name' => 'Theme Fancy',
    'package' => 'fancy',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/fancy',
  ),
  9 => 
  array (
    'name' => 'Theme Flatcolor',
    'package' => 'flatcolor',
    'version' => '2.4.1-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/flatcolor',
  ),
  10 => 
  array (
    'name' => 'Theme Flatcolor2',
    'package' => 'flatcolor2',
    'version' => '2.4.1-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/flatcolor2',
  ),
  11 => 
  array (
    'name' => 'Theme Grayblue',
    'package' => 'grayblue',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/grayblue',
  ),
  12 => 
  array (
    'name' => 'Theme Graylime',
    'package' => 'graylime',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/graylime',
  ),
  13 => 
  array (
    'name' => 'Theme Graypink',
    'package' => 'graypink',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/graypink',
  ),
  14 => 
  array (
    'name' => 'Theme Greyred',
    'package' => 'greyred',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/greyred',
  ),
  15 => 
  array (
    'name' => 'Theme Modern',
    'package' => 'modern',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/modern',
  ),
  16 => 
  array (
    'name' => 'Theme Newwave',
    'package' => 'newwave',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/newwave',
  ),
  17 => 
  array (
    'name' => 'Theme Response',
    'package' => 'response',
    'version' => '2.4.0-4',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/response',
  ),
  18 => 
  array (
    'name' => 'Theme Studio',
    'package' => 'studio',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/studio',
  ),
  19 => 
  array (
    'name' => 'Thinker theme',
    'package' => 'thinker-theme',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/thinker',
  ),
  20 => 
  array (
    'name' => 'Cash Flow Statement Report',
    'package' => 'rep_cash_flow_statement',
    'version' => '2.4.0-2',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/rep_cash_flow_statement',
  ),
  21 => 
  array (
    'name' => 'Requisitions',
    'package' => 'requisitions',
    'version' => '2.4.0-3',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/requisitions',
  ),
  22 => 
  array (
    'name' => 'Inventory Items CSV Import',
    'package' => 'import_items',
    'version' => '2.4.0-3',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/import_items',
  ),
);
